---
title: "compas_facemap2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(stringr)
```

```{r}
faces <- read.csv('C:/Users/kerim/GitHub/compas_analysis/data_faces/faces_data.csv')
faces <- faces %>% select(ï..Target, Race, Gender, Age)
colnames(faces) <- c('target','race','sex','age')
faces$age <- round(faces$age)

head(faces)

faces <- 
  faces %>% 
  mutate(sex = as.factor(sex),
         race = as.factor(race))

faces$age <-
  case_when(faces$age <25 ~ 1,
            faces$age >35 ~ 3,
            TRUE ~ 2)

faces <- 
  faces %>% 
  mutate(feat = paste(race, sex, age, sep='-'))

faces <-
  faces %>%
  select(target, feat) %>%
  group_by(feat) %>%
  mutate(face_count=n()) %>%
  select(-target) %>%
  unique()

def_demographics <- 
  read.csv('C:/Users/kerim/GitHub/compas_analysis/data_dartmouth/BROWARD_CLEAN_SUBSET.csv')
def_demographics <- 
  def_demographics %>% 
  select(id, race, sex, age, block_num)

def_demographics$race <- 
  factor(def_demographics$race, 
         levels = c(1, 2, 3, 4, 5, 6),
         labels = c('W','B','L','A','N','O'))

def_demographics$sex <- 
  factor(def_demographics$sex, 
         levels=c(0, 1),
         labels= c('M','F'))

def_demographics$age <-
  case_when(def_demographics$age <25 ~ 1,
            def_demographics$age >35 ~ 3,
            TRUE ~ 2)
  
def_demographics <- 
  def_demographics %>% 
  mutate(feat = paste(race, sex, age, sep='-'))

def_demographics_count <- 
  def_demographics %>%
  select(id, feat, block_num) %>%
  group_by(feat,block_num) %>% 
  mutate(def_count=n()) %>%
  select(-id) %>%
  unique()

summary <- left_join(def_demographics_count, faces, by='feat')

write.csv(summary, file='def_face_summary.csv')
```

```{r}
library(ggplot2)

summary_gathered <- 
  summary %>% gather('type','count',3:4)

summary_plot <-
  summary_gathered %>%
  filter(block_num == 1) %>%
  ggplot(aes(fill=type, y=count, x=feat)) +
  geom_bar(position='dodge',stat='identity')
summary_plot
```